
# Simple movement Commands
CMD_GO_SIMPLE = 1
CMD_BACK_SIMPLE = 2
CMD_STOP = 3
CMD_LEFT_SIMPLE = 4
CMD_RIGHT_SIMPLE = 5
CMD_TURN_AROUND = 6


# Action commands
CMD_RESET_DIST = 7
CMD_FRONTLEDON = 8
CMD_FRONTLEDOFF = 9
CMD_GREENLEDON = 10
CMD_GREENLEDOFF = 11
CMD_BRAKELEDON = 12
CMD_BRAKELEDOFF = 13
CMD_REDLEDON = 14
CMD_REDLEDOFF = 15
CMD_FRONTBLINK = 16
CMD_BRAKEBLINK = 17
CMD_GREENBLINK = 18
CMD_REDBLINK = 19
CMD_LEDSON = 20
CMD_LEDSOFF = 21
CMD_LEDSBLINK = 22
CMD_BUZZERON = 23
CMD_BUZZEROFF = 24
CMD_MELODYCHARGE = 25
CMD_MELODYFAIL = 26
CMD_LINE_FOLLOW_L = 27
CMD_LINE_FOLLOW_R = 28
CMD_PUSH = 29

# Full movement commands
CMD_GO = 30
CMD_BACK = 31
CMD_GOLEFT = 32
CMD_GORIGHT = 33
CMD_BACKLEFT = 34
CMD_BACKRIGHT = 35
CMD_ROTATELEFT = 36
CMD_ROTATERIGHT = 37


# Rotation axis
CENTER = 38
WHEEL = 39

